services:
  - type: web
    name: ml-proxy
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PROXY_SECRET
        generateValue: true
